version: 2

jobs:
  "go-1.11":
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: make test-ci
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - "go-1.11"
